//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace BuildDatabase
{
    
    public partial class exam
    {
        [PrimaryKey]
        public Int64 id { get; set; }
        
        public String eng { get; set; }
        
        public String jpn { get; set; }
        
    }
    
    public partial class jaen
    {
        [PrimaryKey]
        public Int64 id { get; set; }
        
        public String word { get; set; }
        
        public String phonetic { get; set; }
        
        public String mean { get; set; }
        
    }
    
    
    
}
