//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace BuildDatabase
{
    public partial class examplenew
    {
        public int id { get; set; }
        
        public String content { get; set; }
        
        public String mean { get; set; }
        
        public String trans { get; set; }
        
    }
    
    public partial class javinew
    {
        [PrimaryKey]
        public Int64 id { get; set; }
        
        public String word { get; set; }
        
        public String kana { get; set; }
        
        public String mean { get; set; }
        
    }
    
    public partial class vijanew
    {
        [PrimaryKey]
        public Int64 id { get; set; }
        
        public String word { get; set; }
        
        public String mean { get; set; }
        
    }
    
}
